FROM chatapp-build-image AS build

# copy config for .net
WORKDIR /src
COPY ["chatapp/chatapp.csproj", "chatapp/"]

# install .net dependencies
RUN dotnet restore "chatapp/chatapp.csproj"

# copy the source code(some files are ignored as per .dockerignore)
COPY . .

# run .net unit tests
WORKDIR backendroutingtests
WORKDIR ..

WORKDIR "/src/chatapp"

# run react unit tests(must be run in ClientApp dir)
WORKDIR ClientApp
RUN npm install react-scripts