FROM mcr.microsoft.com/dotnet/sdk:6.0
# Install Node.js

RUN apt-get update && apt-get install -y \
    software-properties-common \
    npm
RUN npm install npm@latest -g && \
    npm install n -g && \
    n latest
RUN node --version
RUN npm --version